// Chinese counterparts of the international About page. Both locales share its layout and assets.
const aboutChineseCopy: Record<string, string> = {
  "Company": "公司介绍",
  "About Camari": "关于卡玛瑞",
  "Established in 2014 and headquartered in Hong Kong, Camari International is a multinational leader specializing in high-performance automotive materials, bespoke interior accessories, and lifestyle products. With regional operating hubs in China, Italy, Japan, and Australia, we deliver technical excellence and seamless supply chain solutions to clients worldwide.": "卡玛瑞国际成立于 2014 年，总部位于香港，是一家专注于高性能汽车材料、定制内饰配件及生活方式产品的跨国领先企业。我们在中国、意大利、日本和澳大利亚设有区域运营中心，为全球客户提供卓越的技术支持和顺畅衔接的供应链解决方案。",
  "Global footprint": "全球布局",
  "Integrated Supply Infrastructure": "一体化供应网络",
  "With established corporate entities across four strategic regions, China, Italy, Japan, and Australia, CAMARI unifies regional supply strengths under one seamless export infrastructure. By aggregating localized specialty products into a centralized export channel, we offer global clients direct access to premium regional materials, optimized logistics, and end-to-end supply chain reliability.": "卡玛瑞在中国、意大利、日本和澳大利亚四个战略区域设立公司实体，通过统一的出口体系整合各地供应优势。我们将各地特色产品汇集至集中的出口渠道，让全球客户能够直接获取优质区域材料，并享有优化的物流服务和可靠的全流程供应链支持。",
  "Central warehousing": "中央仓储",
  "China & Italy": "中国与意大利",
  "Material references": "材料品项",
  "Curated colour & surface library": "精选色彩与表面材料库",
  "Local office & warehouse": "本地办公室与仓库",
  "China, Italy, Japan & Australia": "中国、意大利、日本与澳大利亚",
  "Accessories production plant": "配件生产工厂",
  "Customized interior & lifestyle accessories": "定制内饰及生活方式配件",
  "Quality management": "质量管理",
  "Certified system": "认证管理体系",
  "Automotive quality management": "汽车行业质量管理",
  "Certified production": "认证生产体系",
  "China · Italy · Japan · Australia": "中国 · 意大利 · 日本 · 澳大利亚",
  "Local Service & Global Collaboration": "本地服务与全球协作",
  "Clients work with specialists in their own market, while CAMARI teams share specifications, sampling feedback, and production planning across borders. Central warehousing in China and Italy keeps material access close to each project and coordination consistent from concept to delivery.": "客户可直接与当地市场的专业团队合作，卡玛瑞各地团队则跨区域共享规格要求、打样反馈和生产计划。设于中国和意大利的中央仓储为各类项目提供便利的材料供应，确保从概念构思到最终交付始终保持一致的协作。",
  "Official authorization": "官方授权",
  "Official Distributor of Alcantara": "Alcantara 官方经销商",
  "As the official Asia-Pacific regional distributor for Alcantara®, Camari supplies authentic premium microfibers to key international markets, including Greater China, Japan, Korea, Southeast Asia, Australia, and New Zealand.": "作为 Alcantara® 亚太地区官方经销商，卡玛瑞向大中华区、日本、韩国、东南亚、澳大利亚和新西兰等主要国际市场供应正品Alcantara",
  "Beyond Alcantara, our material library spans luxury bovine leathers, technical woven fabrics, and synthetic materials tailored for automotive upholstery, marine, aviation, and bespoke interior architecture.": "除 Alcantara 外，我们的材料库还涵盖高端牛皮、功能性及羊毛织物及人造革，满足汽车内饰、船舶、航空以及定制室内建筑设计的应用需求。",
  "Manufacturing": "制造能力",
  "Heritage Craft, Certified Precision.": "传承工艺，认证精度。",
  "Rapid Prototyping & In-House Sampling": "快速原型开发与内部打样",
  "Located directly within our China headquarters, our dedicated prototyping lab is staffed by specialized technicians and equipped for cutting, perforation, lamination, quilting, and embroidery. Combined with advanced laser processing, digital printing, and 3D printing capabilities, clients can select from over 1,000 in-stock materials to turn custom design concepts into physical samples with minimal lead times.": "我们的专属打样实验室设于中国总部，配备专业技术人员及裁切、打孔、复合、绗缝和刺绣设备，并结合先进的激光加工、数码印花和 3D 打印能力。客户可从超过 1,000 种现货材料中进行选择，以较短的周期将定制设计概念转化为实物样品。",
  "Automotive-Grade Manufacturing": "汽车级制造",
  "Operating under the strict IATF 16949 international automotive quality management system, our facility is engineered for high-volume, uncompromising precision. From raw material inspection to automated CNC cutting, custom surface treatment, and rigorous end-of-line durability testing, we ensure consistency and OEM compliance across every production run.": "我们的工厂严格遵循 IATF 16949 国际汽车行业质量管理体系，在大批量生产中坚持高精度要求。从原材料检验、自动化 CNC 裁切、定制表面处理，到严格的生产末端耐久性测试，我们确保每个生产批次的一致性，并符合 OEM 要求。",
  "Global Logistics & Warehousing": "全球物流与仓储",
  "Supported by 10,000 m² of central warehousing across China and Italy, alongside strategic regional hubs in Japan and Australia, Camari provides end-to-end supply chain reliability. Our international fulfillment infrastructure guarantees streamlined customs clearance, localized inventory management, and rapid global distribution.": "依托中国和意大利共 10,000 平方米的中央仓储，以及日本和澳大利亚的区域枢纽，卡玛瑞提供可靠的全流程供应链支持。我们的国际交付网络确保高效通关、本地化库存管理及快速的全球配送。",
  "CASA CAMARI office and material showroom interior": "CASA CAMARI 办公室与材料展厅内景",
  "CAMARI China warehouse": "卡玛瑞中国仓库",
  "Alcantara Milan headquarters interior": "Alcantara 米兰总部内景",
  "Speak with our specialists about material specifications, bespoke prototyping, and bulk production.": "与我们的专业团队沟通材料规格、定制打样及批量生产需求。",
  "Our location": "我们的办公地点",
  "Write message": "给我们留言",
  "Ready to integrate premium materials into your next project?": "准备好为您的下一个项目选用优质材料了吗？",
};

export function translateAboutCopy(text: string): string {
  return aboutChineseCopy[text] ?? text;
}
